#version: "3"
#
#services:
#  node-docker:
#    image: selenium/node-docker:4.12.1-20230904
#    volumes:
#      - ./config.toml:/opt/bin/config.toml
#      - ./videos:/opt/selenium/assets
#      - /var/run/docker.sock:/var/run/docker.sock
#    depends_on:
#      - selenium-hub
#    environment:
#      - SE_EVENT_BUS_HOST=selenium-hub
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#
#  selenium-hub:
#    image: selenium/hub:4.12.1-20230904
#    container_name: selenium-hub
#    ports:
#      - "4442:4442"
#      - "4443:4443"
#      - "4444:4444"

version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4442-4444:4442-4444"
    networks:
      - grid

  chrome:
    image: selenium/node-chrome
    container_name: chrome
    shm_size: 2g
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
    networks:
      - grid

  edge:
    image: selenium/node-edge
    container_name: edge
    shm_size: 2g
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
    networks:
      - grid

  firefox:
    image: selenium/node-firefox
    container_name: firefox
    shm_size: 2g
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
    networks:
      - grid

#  chrome_video:
#    image: selenium/video:ffmpeg-4.3.1-20230801
#    volumes:
#      - ./videos:/videos
#    depends_on:
#      - chrome
#    environment:
#      - DISPLAY_CONTAINER_NAME=chrome
#      - FILE_NAME=chrome_video.mp4
#    networks:
#      - grid
#
#  edge_video:
#    image: selenium/video:ffmpeg-4.3.1-20230801
#    volumes:
#      - ./videos:/videos
#    depends_on:
#      - edge
#    environment:
#      - DISPLAY_CONTAINER_NAME=edge
#      - FILE_NAME=edge_video.mp4
#    networks:
#      - grid
#
#  firefox_video:
#    image: selenium/video:ffmpeg-4.3.1-20230801
#    volumes:
#      - ./videos:/videos
#    depends_on:
#      - firefox
#    environment:
#      - DISPLAY_CONTAINER_NAME=firefox
#      - FILE_NAME=firefox_video.mp4
#    networks:
#      - grid

networks:
  grid:
    driver: bridge

